import './js/spinner';
import './js/fetches';
import './js/render-markup';
import './js/theme-btn';
import './js/current-page-underline';
import './js/search-field';
import './js/navigation';
import './js/calendar';
import './js/news-card';
import './js/weather';
import './js/mobile-menu';
import './js/onmount';
import './js/news-card-listner';
import './js/btnUpp';
import './js/header-fixed-position';

import './js/addtoread';
import axios, { isCancel, AxiosError } from 'axios';
const CalendarDates = require('calendar-dates');
const calendarDates = new CalendarDates();
